# Generated by Django 4.2.2 on 2023-06-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('author', models.CharField(max_length=45)),
                ('content', models.TextField()),
                ('thumbnail', models.ImageField(default='default.png', upload_to='thumbnails/')),
            ],
        ),
    ]
